services:
  - type: web
    name: the-arhc-server
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYPAL_ENV
        value: sandbox
      - key: ARHC_PUBLIC_ORIGIN
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYAPAL_SECRET_ID
        sync: false
      - key: PAYPAL_WEBHOOK_ID
        sync: false
      - key: PAYPAL_RETURN_URL
        sync: false
      - key: PAYPAL_CANCEL_URL
        sync: false
